//! Weight definitions for `pallet_tender_chain`.
//!
//! This module defines the [`WeightInfo`] trait only. It deliberately ships no
//! "reference" implementation with invented constants: weights depend on the
//! runtime's own `Config` bounds (`MaxBidders`, `MaxWeights`, …) and on the
//! hardware, so a plausible-looking hard-coded table is worse than none — it
//! reads as authoritative while being fiction.
//!
//! Real benchmarked weights for this repo's runtime live in
//! `runtime/src/weights/pallet_tender_chain.rs`, generated by the Substrate
//! benchmark CLI from `src/benchmarking.rs`. Regenerate with:
//!
//! ```text
//! cargo build --release --features runtime-benchmarks -p solochain-template-node
//! ./target/release/solochain-template-node benchmark pallet \
//!   --pallet pallet_tender_chain --extrinsic '*' --steps 50 --repeat 20 \
//!   --output runtime/src/weights/pallet_tender_chain.rs
//! ```
//!
//! Any other runtime embedding this pallet must benchmark it against its own
//! bounds rather than reusing those numbers.
//!
//! The `()` implementation below is for mocks and tests, where weights are not
//! metered. Never use it in a production runtime.

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};

/// Weight functions needed for pallet_tender_chain.
pub trait WeightInfo {
	/// `w`: number of weighted criteria.
	fn create_tender(w: u32) -> Weight;
	fn publish_tender() -> Weight;
	fn ask_question() -> Weight;
	fn answer_question() -> Weight;
	fn publish_addendum() -> Weight;
	fn commit_bid() -> Weight;
	fn withdraw_commitment() -> Weight;
	fn open_tender() -> Weight;
	/// `p`: number of price-schedule lines.
	fn reveal_bid(p: u32) -> Weight;
	fn appoint_evaluator() -> Weight;
	fn declare_conflict() -> Weight;
	fn activate_evaluator() -> Weight;
	/// `c`: number of criteria scored.
	fn submit_scores(c: u32) -> Weight;
	/// `b`: number of bidders ranked.
	fn award(b: u32) -> Weight;
	fn lodge_challenge() -> Weight;
	fn resolve_challenge() -> Weight;
	/// `b`: number of bonds released.
	fn execute_award(b: u32) -> Weight;
	/// `b`: number of bonds released.
	fn cancel_tender(b: u32) -> Weight;
	fn call_off() -> Weight;
	/// `s`: number of suppliers shortlisted.
	fn publish_shortlist(s: u32) -> Weight;
	/// `p`: number of price-schedule lines in an open bid.
	fn submit_open_bid(p: u32) -> Weight;
	/// `n`: gate transitions processed this block.
	fn on_initialize(n: u32) -> Weight;
}

/// Test/mock implementation. Not metered — never use in production.
impl WeightInfo for () {
	fn create_tender(w: u32) -> Weight {
		Weight::from_parts(20_000_000, 4_000)
			.saturating_add(Weight::from_parts(50_000, 0).saturating_mul(w as u64))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn publish_tender() -> Weight {
		Weight::from_parts(30_000_000, 5_000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn ask_question() -> Weight {
		Weight::from_parts(15_000_000, 3_000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn answer_question() -> Weight {
		Weight::from_parts(15_000_000, 3_000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn publish_addendum() -> Weight {
		Weight::from_parts(25_000_000, 5_000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn commit_bid() -> Weight {
		Weight::from_parts(35_000_000, 5_000)
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn withdraw_commitment() -> Weight {
		Weight::from_parts(35_000_000, 5_000)
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn open_tender() -> Weight {
		Weight::from_parts(18_000_000, 4_000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn reveal_bid(p: u32) -> Weight {
		Weight::from_parts(40_000_000, 5_000)
			.saturating_add(Weight::from_parts(100_000, 0).saturating_mul(p as u64))
			.saturating_add(RocksDbWeight::get().reads(3_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn appoint_evaluator() -> Weight {
		Weight::from_parts(18_000_000, 3_000)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn declare_conflict() -> Weight {
		Weight::from_parts(15_000_000, 3_000)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn activate_evaluator() -> Weight {
		Weight::from_parts(20_000_000, 3_000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
	}
	fn submit_scores(c: u32) -> Weight {
		Weight::from_parts(45_000_000, 6_000)
			.saturating_add(Weight::from_parts(200_000, 0).saturating_mul(c as u64))
			.saturating_add(RocksDbWeight::get().reads(4_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	fn award(b: u32) -> Weight {
		Weight::from_parts(60_000_000, 10_000)
			.saturating_add(Weight::from_parts(2_000_000, 0).saturating_mul(b as u64))
			.saturating_add(RocksDbWeight::get().reads(4_u64).saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(b as u64))))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn lodge_challenge() -> Weight {
		Weight::from_parts(25_000_000, 4_000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn resolve_challenge() -> Weight {
		Weight::from_parts(25_000_000, 4_000)
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(3_u64))
	}
	fn execute_award(b: u32) -> Weight {
		Weight::from_parts(50_000_000, 8_000)
			.saturating_add(Weight::from_parts(3_000_000, 0).saturating_mul(b as u64))
			.saturating_add(RocksDbWeight::get().reads(4_u64).saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(b as u64))))
			.saturating_add(RocksDbWeight::get().writes(3_u64).saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(b as u64))))
	}
	fn cancel_tender(b: u32) -> Weight {
		Weight::from_parts(40_000_000, 8_000)
			.saturating_add(Weight::from_parts(3_000_000, 0).saturating_mul(b as u64))
			.saturating_add(RocksDbWeight::get().reads(3_u64).saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(b as u64))))
			.saturating_add(RocksDbWeight::get().writes(2_u64).saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(b as u64))))
	}
	fn submit_open_bid(p: u32) -> Weight {
		Weight::from_parts(40_000_000, 6_000)
			.saturating_add(Weight::from_parts(100_000, 0).saturating_mul(p as u64))
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	fn publish_shortlist(s: u32) -> Weight {
		Weight::from_parts(20_000_000, 4_000)
			.saturating_add(Weight::from_parts(2_000_000, 0).saturating_mul(s as u64))
			.saturating_add(RocksDbWeight::get().reads(2_u64))
			.saturating_add(RocksDbWeight::get().writes(2_u64))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(s as u64)))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(s as u64)))
	}
	fn call_off() -> Weight {
		Weight::from_parts(15_000_000, 3_000)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	fn on_initialize(n: u32) -> Weight {
		Weight::from_parts(10_000_000, 3_000)
			.saturating_add(Weight::from_parts(8_000_000, 0).saturating_mul(n as u64))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
			.saturating_add(RocksDbWeight::get().reads((2_u64).saturating_mul(n as u64)))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(n as u64)))
	}
}
