
//! Autogenerated weights for `pallet_tender_chain`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 47.0.0
//! DATE: 2026-09-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `instance-20260310-160313`, CPU: `AMD EPYC 7B12`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/solochain-template-node
// benchmark
// pallet
// --pallet
// pallet_tender_chain
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// runtime/src/weights/pallet_tender_chain.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_tender_chain`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_tender_chain::WeightInfo for WeightInfo<T> {
	/// Storage: `TenderChain::NextTenderId` (r:1 w:1)
	/// Proof: `TenderChain::NextTenderId` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Tenders` (r:0 w:1)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::TenderRawId` (r:0 w:1)
	/// Proof: `TenderChain::TenderRawId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// The range of component `w` is `[1, 20]`.
	fn create_tender(_w: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `1489`
		// Minimum execution time: 15_200_000 picoseconds.
		Weight::from_parts(16_860_742, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:1)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::DeadlineWheel` (r:3 w:3)
	/// Proof: `TenderChain::DeadlineWheel` (`max_values`: None, `max_size`: Some(334), added: 2809, mode: `MaxEncodedLen`)
	fn publish_tender() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `391`
		//  Estimated: `9417`
		// Minimum execution time: 27_980_000 picoseconds.
		Weight::from_parts(28_990_000, 0)
			.saturating_add(Weight::from_parts(0, 9417))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:0)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::NextQuestionId` (r:1 w:1)
	/// Proof: `TenderChain::NextQuestionId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Questions` (r:0 w:1)
	/// Proof: `TenderChain::Questions` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	fn ask_question() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `390`
		//  Estimated: `4282`
		// Minimum execution time: 26_410_000 picoseconds.
		Weight::from_parts(28_250_000, 0)
			.saturating_add(Weight::from_parts(0, 4282))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:0)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Questions` (r:1 w:1)
	/// Proof: `TenderChain::Questions` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	fn answer_question() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `473`
		//  Estimated: `4282`
		// Minimum execution time: 22_200_000 picoseconds.
		Weight::from_parts(23_089_000, 0)
			.saturating_add(Weight::from_parts(0, 4282))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:1)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Addenda` (r:1 w:1)
	/// Proof: `TenderChain::Addenda` (`max_values`: None, `max_size`: Some(1333), added: 3808, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::DeadlineWheel` (r:2 w:2)
	/// Proof: `TenderChain::DeadlineWheel` (`max_values`: None, `max_size`: Some(334), added: 2809, mode: `MaxEncodedLen`)
	fn publish_addendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `390`
		//  Estimated: `6608`
		// Minimum execution time: 31_380_000 picoseconds.
		Weight::from_parts(32_500_000, 0)
			.saturating_add(Weight::from_parts(0, 6608))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:0)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::BidCommitments` (r:1 w:1)
	/// Proof: `TenderChain::BidCommitments` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::EvaluatorSet` (r:1 w:0)
	/// Proof: `TenderChain::EvaluatorSet` (`max_values`: None, `max_size`: Some(138), added: 2613, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::ShortlistSource` (r:1 w:0)
	/// Proof: `TenderChain::ShortlistSource` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Participants` (r:1 w:1)
	/// Proof: `TenderChain::Participants` (`max_values`: None, `max_size`: Some(4118), added: 6593, mode: `MaxEncodedLen`)
	fn commit_bid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `350`
		//  Estimated: `7583`
		// Minimum execution time: 48_790_000 picoseconds.
		Weight::from_parts(50_510_000, 0)
			.saturating_add(Weight::from_parts(0, 7583))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:0)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::BidCommitments` (r:1 w:1)
	/// Proof: `TenderChain::BidCommitments` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Participants` (r:1 w:1)
	/// Proof: `TenderChain::Participants` (`max_values`: None, `max_size`: Some(4118), added: 6593, mode: `MaxEncodedLen`)
	fn withdraw_commitment() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `558`
		//  Estimated: `7583`
		// Minimum execution time: 43_820_000 picoseconds.
		Weight::from_parts(45_560_000, 0)
			.saturating_add(Weight::from_parts(0, 7583))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:1)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Participants` (r:1 w:0)
	/// Proof: `TenderChain::Participants` (`max_values`: None, `max_size`: Some(4118), added: 6593, mode: `MaxEncodedLen`)
	fn open_tender() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `447`
		//  Estimated: `7583`
		// Minimum execution time: 22_230_000 picoseconds.
		Weight::from_parts(24_260_000, 0)
			.saturating_add(Weight::from_parts(0, 7583))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:0)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Reveals` (r:1 w:1)
	/// Proof: `TenderChain::Reveals` (`max_values`: None, `max_size`: Some(1387), added: 3862, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::BidCommitments` (r:1 w:0)
	/// Proof: `TenderChain::BidCommitments` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 64]`.
	fn reveal_bid(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `527`
		//  Estimated: `4852`
		// Minimum execution time: 31_290_000 picoseconds.
		Weight::from_parts(34_402_220, 0)
			.saturating_add(Weight::from_parts(0, 4852))
			// Standard Error: 5_608
			.saturating_add(Weight::from_parts(35_032, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:0)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::BidCommitments` (r:1 w:0)
	/// Proof: `TenderChain::BidCommitments` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::EvaluatorSet` (r:1 w:1)
	/// Proof: `TenderChain::EvaluatorSet` (`max_values`: None, `max_size`: Some(138), added: 2613, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::AppointedEvaluatorCount` (r:1 w:1)
	/// Proof: `TenderChain::AppointedEvaluatorCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn appoint_evaluator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `350`
		//  Estimated: `4282`
		// Minimum execution time: 31_350_000 picoseconds.
		Weight::from_parts(32_830_000, 0)
			.saturating_add(Weight::from_parts(0, 4282))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TenderChain::EvaluatorSet` (r:1 w:1)
	/// Proof: `TenderChain::EvaluatorSet` (`max_values`: None, `max_size`: Some(138), added: 2613, mode: `MaxEncodedLen`)
	fn declare_conflict() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `299`
		//  Estimated: `3603`
		// Minimum execution time: 17_520_000 picoseconds.
		Weight::from_parts(19_070_000, 0)
			.saturating_add(Weight::from_parts(0, 3603))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:0)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::EvaluatorSet` (r:1 w:1)
	/// Proof: `TenderChain::EvaluatorSet` (`max_values`: None, `max_size`: Some(138), added: 2613, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::ActiveEvaluatorCount` (r:1 w:1)
	/// Proof: `TenderChain::ActiveEvaluatorCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn activate_evaluator() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `538`
		//  Estimated: `4282`
		// Minimum execution time: 25_410_000 picoseconds.
		Weight::from_parts(27_821_000, 0)
			.saturating_add(Weight::from_parts(0, 4282))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:0)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::EvaluatorSet` (r:1 w:0)
	/// Proof: `TenderChain::EvaluatorSet` (`max_values`: None, `max_size`: Some(138), added: 2613, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Reveals` (r:1 w:0)
	/// Proof: `TenderChain::Reveals` (`max_values`: None, `max_size`: Some(1387), added: 3862, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Scores` (r:3 w:1)
	/// Proof: `TenderChain::Scores` (`max_values`: None, `max_size`: Some(253), added: 2728, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 20]`.
	fn submit_scores(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1059 + c * (15 ±0)`
		//  Estimated: `9174`
		// Minimum execution time: 57_600_000 picoseconds.
		Weight::from_parts(61_456_148, 0)
			.saturating_add(Weight::from_parts(0, 9174))
			// Standard Error: 14_709
			.saturating_add(Weight::from_parts(101_169, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:1)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::ActiveEvaluatorCount` (r:1 w:0)
	/// Proof: `TenderChain::ActiveEvaluatorCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Reveals` (r:128 w:0)
	/// Proof: `TenderChain::Reveals` (`max_values`: None, `max_size`: Some(1387), added: 3862, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Participants` (r:1 w:0)
	/// Proof: `TenderChain::Participants` (`max_values`: None, `max_size`: Some(4118), added: 6593, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Scores` (r:512 w:0)
	/// Proof: `TenderChain::Scores` (`max_values`: None, `max_size`: Some(253), added: 2728, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::DeadlineWheel` (r:1 w:1)
	/// Proof: `TenderChain::DeadlineWheel` (`max_values`: None, `max_size`: Some(334), added: 2809, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Outcomes` (r:0 w:1)
	/// Proof: `TenderChain::Outcomes` (`max_values`: None, `max_size`: Some(8801), added: 11276, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 128]`.
	fn award(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `682 + b * (779 ±0)`
		//  Estimated: `7583 + b * (10912 ±0)`
		// Minimum execution time: 315_840_000 picoseconds.
		Weight::from_parts(320_970_000, 0)
			.saturating_add(Weight::from_parts(0, 7583))
			// Standard Error: 300_989
			.saturating_add(Weight::from_parts(327_970_114, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((5_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(Weight::from_parts(0, 10912).saturating_mul(b.into()))
	}
	/// Storage: `TenderChain::Outcomes` (r:1 w:0)
	/// Proof: `TenderChain::Outcomes` (`max_values`: None, `max_size`: Some(8801), added: 11276, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::BidCommitments` (r:1 w:0)
	/// Proof: `TenderChain::BidCommitments` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::NextChallengeId` (r:1 w:1)
	/// Proof: `TenderChain::NextChallengeId` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::OpenChallengeCount` (r:1 w:1)
	/// Proof: `TenderChain::OpenChallengeCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Tenders` (r:1 w:1)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Challenges` (r:0 w:1)
	/// Proof: `TenderChain::Challenges` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	fn lodge_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `865`
		//  Estimated: `12266`
		// Minimum execution time: 43_610_000 picoseconds.
		Weight::from_parts(46_270_000, 0)
			.saturating_add(Weight::from_parts(0, 12266))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `TenderChain::Challenges` (r:1 w:1)
	/// Proof: `TenderChain::Challenges` (`max_values`: None, `max_size`: Some(147), added: 2622, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::OpenChallengeCount` (r:1 w:1)
	/// Proof: `TenderChain::OpenChallengeCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Tenders` (r:1 w:1)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	fn resolve_challenge() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `692`
		//  Estimated: `4282`
		// Minimum execution time: 31_620_000 picoseconds.
		Weight::from_parts(33_531_000, 0)
			.saturating_add(Weight::from_parts(0, 4282))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:1)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::OpenChallengeCount` (r:1 w:0)
	/// Proof: `TenderChain::OpenChallengeCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Outcomes` (r:1 w:1)
	/// Proof: `TenderChain::Outcomes` (`max_values`: None, `max_size`: Some(8801), added: 11276, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Participants` (r:1 w:0)
	/// Proof: `TenderChain::Participants` (`max_values`: None, `max_size`: Some(4118), added: 6593, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::BidCommitments` (r:128 w:128)
	/// Proof: `TenderChain::BidCommitments` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:128 w:128)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 128]`.
	fn execute_award(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `418 + b * (309 ±0)`
		//  Estimated: `12266 + b * (2603 ±0)`
		// Minimum execution time: 70_530_000 picoseconds.
		Weight::from_parts(14_877_647, 0)
			.saturating_add(Weight::from_parts(0, 12266))
			// Standard Error: 81_621
			.saturating_add(Weight::from_parts(32_110_948, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(b.into()))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:1)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Participants` (r:1 w:0)
	/// Proof: `TenderChain::Participants` (`max_values`: None, `max_size`: Some(4118), added: 6593, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::BidCommitments` (r:128 w:128)
	/// Proof: `TenderChain::BidCommitments` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:128 w:128)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 128]`.
	fn cancel_tender(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `128 + b * (273 ±0)`
		//  Estimated: `7583 + b * (2603 ±0)`
		// Minimum execution time: 51_209_000 picoseconds.
		Weight::from_parts(53_260_000, 0)
			.saturating_add(Weight::from_parts(0, 7583))
			// Standard Error: 47_965
			.saturating_add(Weight::from_parts(30_095_724, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().reads((2_u64).saturating_mul(b.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((2_u64).saturating_mul(b.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(b.into()))
	}
	/// Storage: `TenderChain::PanelTender` (r:1 w:0)
	/// Proof: `TenderChain::PanelTender` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Tenders` (r:1 w:0)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::PanelPool` (r:1 w:0)
	/// Proof: `TenderChain::PanelPool` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	fn call_off() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `678`
		//  Estimated: `4282`
		// Minimum execution time: 28_751_000 picoseconds.
		Weight::from_parts(30_280_000, 0)
			.saturating_add(Weight::from_parts(0, 4282))
			.saturating_add(T::DbWeight::get().reads(3))
			// PROVISIONAL, hand-added: call-offs are now stored (CallOffCount,
			// CallOffs). Overwritten by the next benchmark run.
			.saturating_add(Weight::from_parts(10_000_000, 3_000))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:1)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Reveals` (r:128 w:0)
	/// Proof: `TenderChain::Reveals` (`max_values`: None, `max_size`: Some(1387), added: 3862, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::ShortlistCount` (r:0 w:1)
	/// Proof: `TenderChain::ShortlistCount` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Shortlist` (r:0 w:128)
	/// Proof: `TenderChain::Shortlist` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// The range of component `s` is `[1, 128]`.
	fn publish_shortlist(s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `486 + s * (113 ±0)`
		//  Estimated: `4282 + s * (3862 ±0)`
		// Minimum execution time: 32_270_000 picoseconds.
		Weight::from_parts(18_562_711, 0)
			.saturating_add(Weight::from_parts(0, 4282))
			// Standard Error: 26_939
			.saturating_add(Weight::from_parts(8_403_757, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(s.into())))
			.saturating_add(T::DbWeight::get().writes(2))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
			.saturating_add(Weight::from_parts(0, 3862).saturating_mul(s.into()))
	}
	/// Storage: `TenderChain::Tenders` (r:1 w:0)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::BidCommitments` (r:1 w:1)
	/// Proof: `TenderChain::BidCommitments` (`max_values`: None, `max_size`: Some(120), added: 2595, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::EvaluatorSet` (r:1 w:0)
	/// Proof: `TenderChain::EvaluatorSet` (`max_values`: None, `max_size`: Some(138), added: 2613, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::ShortlistSource` (r:1 w:0)
	/// Proof: `TenderChain::ShortlistSource` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Participants` (r:1 w:1)
	/// Proof: `TenderChain::Participants` (`max_values`: None, `max_size`: Some(4118), added: 6593, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Reveals` (r:0 w:1)
	/// Proof: `TenderChain::Reveals` (`max_values`: None, `max_size`: Some(1387), added: 3862, mode: `MaxEncodedLen`)
	/// The range of component `p` is `[1, 64]`.
	fn submit_open_bid(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `350`
		//  Estimated: `7583`
		// Minimum execution time: 55_420_000 picoseconds.
		Weight::from_parts(59_777_225, 0)
			.saturating_add(Weight::from_parts(0, 7583))
			// Standard Error: 9_491
			.saturating_add(Weight::from_parts(64_199, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `TenderChain::DeadlineWheel` (r:1 w:1)
	/// Proof: `TenderChain::DeadlineWheel` (`max_values`: None, `max_size`: Some(334), added: 2809, mode: `MaxEncodedLen`)
	/// Storage: `TenderChain::Tenders` (r:16 w:16)
	/// Proof: `TenderChain::Tenders` (`max_values`: None, `max_size`: Some(817), added: 3292, mode: `MaxEncodedLen`)
	/// The range of component `n` is `[0, 16]`.
	fn on_initialize(n: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `181 + n * (228 ±0)`
		//  Estimated: `3799 + n * (3292 ±0)`
		// Minimum execution time: 3_700_000 picoseconds.
		Weight::from_parts(8_900_456, 0)
			.saturating_add(Weight::from_parts(0, 3799))
			// Standard Error: 37_210
			.saturating_add(Weight::from_parts(10_188_144, 0).saturating_mul(n.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(n.into())))
			.saturating_add(T::DbWeight::get().writes(1))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(n.into())))
			.saturating_add(Weight::from_parts(0, 3292).saturating_mul(n.into()))
	}
	/// PROVISIONAL, hand-added — not measured. Modelled on `create_tender`'s
	/// per-criterion cost with one `Tenders` read and write. Overwritten by the
	/// next benchmark run.
	fn amend_criteria(w: u32, ) -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4282))
			.saturating_add(Weight::from_parts(200_000, 0).saturating_mul(w.into()))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// PROVISIONAL, hand-added — not measured. One `Policy` write. Overwritten
	/// by the next benchmark run.
	fn set_policy() -> Weight {
		Weight::from_parts(15_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}
}
